# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

I_binder_naive <- function(CI, version = 0L, Const_Binder = 0.5) {
    .Call('_fastbinder_I_binder_naive', PACKAGE = 'fastbinder', CI, version, Const_Binder)
}

I_binder_opt <- function(CI, version = 0L, Const_Binder = 0.5) {
    .Call('_fastbinder_I_binder_opt', PACKAGE = 'fastbinder', CI, version, Const_Binder)
}

I_binder_parallel <- function(CI, version = 0L, Const_Binder = 0.5) {
    .Call('_fastbinder_I_binder_parallel', PACKAGE = 'fastbinder', CI, version, Const_Binder)
}

